use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

/// Chunking must match the reference Python implementation exactly. The golden
/// file is generated by the snippet in the plan for this task.
#[test]
fn chunking_matches_the_python_reference() {
    let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures");
    let golden: BTreeMap<String, Vec<String>> =
        serde_json::from_str(&fs::read_to_string(root.join("golden.json")).unwrap()).unwrap();

    assert!(!golden.is_empty(), "golden fixture is empty");

    for (name, expected) in &golden {
        let text = fs::read_to_string(root.join("notes").join(name)).unwrap();
        let actual = cowork_memory::corpus::chunk_note(name, &text);

        assert_eq!(
            actual.len(),
            expected.len(),
            "{name}: chunk count differs\n  actual:   {actual:#?}\n  expected: {expected:#?}"
        );
        for (i, (a, e)) in actual.iter().zip(expected.iter()).enumerate() {
            assert_eq!(a, e, "{name}: chunk {i} differs");
        }
    }
}
